
databases:
  - name: plusminus
    databaseName: plusminus
    user: plusminus
    region: singapore

services:
  - type: web
    name: plusminus
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: plusminus
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

